/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as PencarianRouteImport } from './routes/pencarian'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const PencarianRoute = PencarianRouteImport.update({
  id: '/pencarian',
  path: '/pencarian',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdukRoute,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdukRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keranjang': typeof KeranjangRoute
  '/lookbook': typeof LookbookRoute
  '/pencarian': typeof PencarianRoute
  '/produk': typeof ProdukRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keranjang': typeof KeranjangRoute
  '/lookbook': typeof LookbookRoute
  '/pencarian': typeof PencarianRoute
  '/wishlist': typeof WishlistRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keranjang': typeof KeranjangRoute
  '/lookbook': typeof LookbookRoute
  '/pencarian': typeof PencarianRoute
  '/produk': typeof ProdukRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/keranjang'
    | '/lookbook'
    | '/pencarian'
    | '/produk'
    | '/wishlist'
    | '/produk/$slug'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keranjang'
    | '/lookbook'
    | '/pencarian'
    | '/wishlist'
    | '/produk/$slug'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/keranjang'
    | '/lookbook'
    | '/pencarian'
    | '/produk'
    | '/wishlist'
    | '/produk/$slug'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeranjangRoute: typeof KeranjangRoute
  LookbookRoute: typeof LookbookRoute
  PencarianRoute: typeof PencarianRoute
  ProdukRoute: typeof ProdukRouteWithChildren
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencarian': {
      id: '/pencarian'
      path: '/pencarian'
      fullPath: '/pencarian'
      preLoaderRoute: typeof PencarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof ProdukRoute
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof ProdukRoute
    }
  }
}

interface ProdukRouteChildren {
  ProdukSlugRoute: typeof ProdukSlugRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

const ProdukRouteChildren: ProdukRouteChildren = {
  ProdukSlugRoute: ProdukSlugRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}

const ProdukRouteWithChildren =
  ProdukRoute._addFileChildren(ProdukRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeranjangRoute: KeranjangRoute,
  LookbookRoute: LookbookRoute,
  PencarianRoute: PencarianRoute,
  ProdukRoute: ProdukRouteWithChildren,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
